/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hms.gui;

import com.hms.model.Patient;
import com.hms.model.Doctor;
import java.util.ArrayList;

/**
 *
 * @author solox
 */
public class MainDashboardGUI extends javax.swing.JFrame {

    private ArrayList<Patient> patientList;
    private ArrayList<Doctor> doctorList;

    /**
     * Creates new form MainDashboardGUI
     */
    public MainDashboardGUI(ArrayList<Patient> patientList, ArrayList<Doctor> doctorList) {
        this.patientList = patientList;
        this.doctorList = doctorList;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helloworld = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnHist = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        btnBlood = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        setBackground(new java.awt.Color(255, 255, 255));

        helloworld.setBackground(new java.awt.Color(37, 99, 235));
        helloworld.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        helloworld.setForeground(new java.awt.Color(31, 41, 55));
        helloworld.setText("Welcome to HMS");
        helloworld.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnReg.setBackground(new java.awt.Color(37, 99, 235));
        btnReg.setForeground(new java.awt.Color(255, 255, 255));
        btnReg.setText("1. Patient Registration");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        btnDoc.setBackground(new java.awt.Color(37, 99, 235));
        btnDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnDoc.setText("2. Doctor Reservation");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnHist.setBackground(new java.awt.Color(37, 99, 235));
        btnHist.setForeground(new java.awt.Color(255, 255, 255));
        btnHist.setText("3. Patient History       ");
        btnHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistActionPerformed(evt);
            }
        });

        btnTest.setBackground(new java.awt.Color(37, 99, 235));
        btnTest.setForeground(new java.awt.Color(255, 255, 255));
        btnTest.setText("4. Test Results            ");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnBlood.setBackground(new java.awt.Color(37, 99, 235));
        btnBlood.setForeground(new java.awt.Color(255, 255, 255));
        btnBlood.setText("5. Blood Bank            ");
        btnBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodActionPerformed(evt);
            }
        });

        btnPay.setBackground(new java.awt.Color(37, 99, 235));
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("6. Payment                ");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(37, 99, 235));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("0. Exit System            ");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(helloworld))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnReg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHist, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDoc)
                            .addComponent(btnTest, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helloworld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBlood)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {                                       
        new PatientRegistrationGUI(patientList).setVisible(true);
    }                                      

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {                                       
        new DoctorReservationGUI(doctorList).setVisible(true);
    }                                      

    private void btnHistActionPerformed(java.awt.event.ActionEvent evt) {                                        
        new PatientHistoryGUI(patientList).setVisible(true);
    }                                       

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {                                        
        new TestResultsGUI(patientList).setVisible(true);
    }                                       

    private void btnBloodActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new BloodBankGUI().setVisible(true);
    }                                        

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {                                       
        new PaymentGUI().setVisible(true);
    }                                      

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.exit(0);
    }                                       



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlood;
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHist;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel helloworld;
    // End of variables declaration//GEN-END:variables
}
